### ISSUE TITLE
按词搜索时报错

### ISSUE THREAD

**Issue by Seele0oO** [lilydjwg/luoxu#11]
后端报错
```
[I 01-29 11:42:43.324 web_log:211] 192.168.10.102 [29/Jan/2024:11:42:43 +0000] "GET /luoxu/search?g=1243169617&q=1&sender=6152264879 HTTP/1.1" 500 245 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0" remote_address=192.168.10.102 request_start_time=[29/Jan/2024:11:42:43 +0000] first_request_line=GET /luoxu/search?g=HIND&q=1&sender=HIND HTTP/1.1 response_status=500 response_size=245 request_header={'Referer': '-', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0'

[E 01-29 11:42:59.756 web_protocol:421] Error handling request
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 452, in _handle_request
        resp = await request_handler(request)
      File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 543, in _handle
        resp = await handler(request)
      File "/root/luoxu/luoxu/web.py", line 27, in get
        res = await self._get(request)
      File "/root/luoxu/luoxu/web.py", line 53, in _get
        groupinfo, messages = await self.dbconn.search(q)
      File "/root/luoxu/luoxu/db.py", line 167, in search
        ret += await self._search_one_year(
      File "/root/luoxu/luoxu/db.py", line 197, in _search_one_year
        query = text_to_query(q.terms.strip())
      File "/root/luoxu/luoxu/indexing.py", line 13, in text_to_query
        return querytrans.transform(s)
    AttributeError: module 'querytrans' has no attribute 'transform'
```
删去 `&q=1` 参数都能正常查询。

运行目录如下
```
root@luoxu:~/luoxu# ls -la
total 824
drwxr-xr-x  9 root root   4096 Jan 29 11:45 .
drwx------ 11 root root   4096 Jan 29 10:54 ..
drwxr-xr-x  8 root root   4096 Jan 29 09:31 .git
-rw-r--r--  1 root root    140 Jan 29 09:31 .gitignore
-rw-r--r--  1 root root  35149 Jan 29 09:31 LICENSE
-rw-r--r--  1 root root     95 Jan 29 09:31 MANIFEST.in
-rw-r--r--  1 root root   3794 Jan 29 09:31 README.md
drwxr-xr-x  2 root root   4096 Jan 29 11:32 cache
-rw-r--r--  1 root root    954 Jan 29 11:28 config.toml
-rw-r--r--  1 root root    795 Jan 29 09:31 config.toml.example
-rwxrwxrwx  1 root root   5316 Jan 29 09:31 dbsetup.sql
-rw-r--r--  1 root root   7376 Jan 29 09:31 ghost.jpg
-rwxr-xr-x  1 root root 618864 Jan 29 11:35 libquerytrans.so
drwxr-xr-x  4 root root   4096 Jan 29 11:25 luoxu
drwxr-xr-x  4 root root   4096 Jan 29 09:52 luoxu-cutwords
drwxr-xr-x  4 root root   4096 Jan 29 09:31 luoxu_plugins
-rw-r--r--  1 root root  86016 Jan 29 11:45 luoxubot.session
-rw-r--r--  1 root root   5269 Jan 29 09:31 nobody.jpg
-rw-r--r--  1 root root    817 Jan 29 09:31 pyproject.toml
drwxr-xr-x  4 root root   4096 Jan 29 09:42 querytrans
-rw-r--r--  1 root root    687 Jan 29 09:31 requirements.txt
drwxr-xr-x  2 root root   4096 Jan 29 09:31 scripts
-rw-r--r--  1 root root   2571 Jan 29 09:31 update-2022-06-23.md
```
luoxu-cutwords编译产物链接到了/usr/bin

前端显示

```
SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)
```

**Comment by lilydjwg** [comment]
把 libquerytrans.so 重命名一下，`lib` 前缀去掉。

**Comment by Seele0oO** [comment]
好耶，能用了，谢谢！
