### ISSUE TITLE
asyncpg.exceptions.CheckViolationError: no partition of relation "messages" found for row

### ISSUE THREAD

**Issue by rde9** [lilydjwg/luoxu#14]
接受新消息时有如下报错：

```bash
[I 04-04 13:34:53.506 db:42]  newmsg <[REDACTED]> [3233261] [REDACTED]
[E 04-04 13:34:53.508 updates:586] Unhandled exception on on_message
    Traceback (most recent call last):
      File "/var/lib/postgresql/.local/lib/python3.9/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
        await callback(event)
      File "/home/luoxu/luoxu/__main__.py", line 55, in on_message
        await dbstore.insert_messages([msg], update_loaded, use_ocr)
      File "/home/luoxu/luoxu/db.py", line 64, in insert_messages
        await self._insert_one_message(conn, msg, text)
      File "/home/luoxu/luoxu/db.py", line 43, in _insert_one_message
        await conn.execute(sql,
      File "/var/lib/postgresql/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 353, in execute
        _, status, _ = await self._execute(
      File "/var/lib/postgresql/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 1794, in _execute
        result, _ = await self.__execute(
      File "/var/lib/postgresql/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 1892, in __execute
        result, stmt = await self._do_execute(
      File "/var/lib/postgresql/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 1945, in _do_execute
        result = await executor(stmt, None)
      File "asyncpg/protocol/protocol.pyx", line 207, in bind_execute
    asyncpg.exceptions.CheckViolationError: no partition of relation "messages" found for row
    DETAIL:  Partition key of the failing row contains (created_at) = (2024-04-04 13:34:52-04).
[I 04-04 13:34:59.526 db:42]  newmsg <[REDACTED]> [3233262] [REDACTED]
[E 04-04 13:34:59.528 updates:586] Unhandled exception on on_message
    Traceback (most recent call last):
      File "/var/lib/postgresql/.local/lib/python3.9/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
        await callback(event)
      File "/home/luoxu/luoxu/__main__.py", line 55, in on_message
        await dbstore.insert_messages([msg], update_loaded, use_ocr)
      File "/home/luoxu/luoxu/db.py", line 64, in insert_messages
        await self._insert_one_message(conn, msg, text)
      File "/home/luoxu/luoxu/db.py", line 43, in _insert_one_message
        await conn.execute(sql,
      File "/var/lib/postgresql/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 353, in execute
以下相同
```
在 luoxu-web 中进行搜索操作时
```bash
500 Internal Server Error

Server got itself in trouble
```

**Comment by lilydjwg** [comment]
是不是需要创建新一年的分区表啦？

**Comment by rde9** [comment]
![Snipaste_2024-04-05_11-02-18](https://github.com/lilydjwg/luoxu/assets/41101885/25a230e1-809a-4033-bb49-a91bd6424e7c)
很奇怪，4月2日我还有过搜索记录，一切正常，但现在y2024确实莫名其妙不见了
已手动 CREATE TABLE messages_y2024 解决，感谢

**Comment by Seele0oO** [comment]
![Image](https://github.com/user-attachments/assets/70556623-4ffa-4400-8b81-fce5058ac2f2)

今天刚解决这个问题，不过我不确定我能否提前创建未来10年的partitio来避免这个问题。

还是使用 pg_cron 插件每年执行一次？

**Comment by lilydjwg** [comment]
> 不过我不确定我能否提前创建未来10年的partitio来避免这个问题。

可以。你提前创建一百年的都行。
